spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop # jdbc:h2:~/jpashop \uC774\uAC78\uB85C \uC0DD\uC131\uD558\uACE0 \uC811\uC18D\uC740 \uC55E \uACBD\uB85C\uB85C \uC811\uC18D
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true system.out\uC73C\uB85C \uCC0D\uB294 sql\uC774\uAE30\uC5D0 \uC0AC\uC6A9\uC744 \uC9C0\uC591\uD55C\uB2E4. logger\uB97C \uD1B5\uD574 logging\uC744 \uD558\uB3C4\uB85D \uC544\uB798\uC640 \uAC19\uC774 \uC124\uC815\uD55C\uB2E4.
        format_sql: true

logging:
  level:
    sql: debug
#    org.hibernate.type: trace