spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop # jdbc:h2:~/jpashop 이걸로 생성하고 접속은 앞 경로로 접속
#    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true => system.out으로 찍는 sql이기에 사용을 지양한다. logger를 통해 logging을 하도록 아래와 같이 설정한다.
        format_sql: true
        default_batch_fetch_size: 100 # in에 들어가는 개수 : 100 ~ 1000사이를 권장한다.

logging:
  level:
    sql: debug
#    org.hibernate.type: trace
